[colors.primary]
background = '#131317'
foreground = '#e5e1e7'

[colors.cursor]
text = '#131317'
cursor = '#e5e1e7'

[colors.vi_mode_cursor]
text = '#131317'
cursor = '#c5c0ff'

[colors.search.matches]
foreground = '#474650'
background = '#fcafe1'

[colors.search.focused_match]
foreground = '#474650'
background = '#c5c0ff'

[colors.footer_bar]
foreground = '#474650'
background = '#e5e1e7'

[colors.hints.start]
foreground = '#474650'
background = '#c7c3e3'

[colors.hints.end]
foreground = '#474650'
background = '#c7c3e3'

[colors.selection]
text = '#c8c5d1'
background = '#474650'


[colors.normal]
black   = '#474650'
red     = '#ffb4ab'
green   = '#c5c0ff'
yellow  = '#c7c3e3'
blue    = '#fcafe1'
magenta = '#c5c0ff'
cyan    = '#c7c3e3'
white   = '#e5e1e7'


[colors.bright]
black   = '#928f9b'
red     = '#ffb4ab'
green   = '#c5c0ff'
yellow  = '#c7c3e3'
blue    = '#fcafe1'
magenta = '#c5c0ff'
cyan    = '#c7c3e3'
white   = '#e5e1e7'


[colors.dim]
black   = '#474650'
red     = '#ffb4ab'
green   = '#c5c0ff'
yellow  = '#c7c3e3'
blue    = '#fcafe1'
magenta = '#c5c0ff'
cyan    = '#c7c3e3'
white   = '#e5e1e7'
