[colors.primary]
background = '#16130f'
foreground = '#e9e1da'

[colors.cursor]
text = '#16130f'
cursor = '#e9e1da'

[colors.vi_mode_cursor]
text = '#16130f'
cursor = '#ffd7a4'

[colors.search.matches]
foreground = '#4e453a'
background = '#dbe3a9'

[colors.search.focused_match]
foreground = '#4e453a'
background = '#ffd7a4'

[colors.footer_bar]
foreground = '#4e453a'
background = '#e9e1da'

[colors.hints.start]
foreground = '#4e453a'
background = '#d9c3a9'

[colors.hints.end]
foreground = '#4e453a'
background = '#d9c3a9'

[colors.selection]
text = '#d2c4b6'
background = '#4e453a'


[colors.normal]
black   = '#4e453a'
red     = '#ffb4ab'
green   = '#ffd7a4'
yellow  = '#d9c3a9'
blue    = '#dbe3a9'
magenta = '#e9c089'
cyan    = '#d9c3a9'
white   = '#e9e1da'


[colors.bright]
black   = '#9b8f82'
red     = '#ffb4ab'
green   = '#ffd7a4'
yellow  = '#d9c3a9'
blue    = '#dbe3a9'
magenta = '#e9c089'
cyan    = '#d9c3a9'
white   = '#e9e1da'


[colors.dim]
black   = '#4e453a'
red     = '#ffb4ab'
green   = '#ffd7a4'
yellow  = '#d9c3a9'
blue    = '#dbe3a9'
magenta = '#e9c089'
cyan    = '#d9c3a9'
white   = '#e9e1da'
