[colors.primary]
background = '#171210'
foreground = '#ece0db'
 
[colors.cursor]
text = '#ece0db'
cursor = '#d6c3b8' 
 
[colors.vi_mode_cursor]
text = '#171210'
cursor = '#fbb88e' 
 
[colors.search.matches]
foreground = '#52443c' 
background = '#c7cb87' 
 
[colors.search.focused_match]
foreground = '#52443c' 
background = '#fbb88e' 
 
[colors.footer_bar]
foreground = '#52443c' 
background = '#ece0db' 
 
[colors.hints.start]
foreground = '#52443c' 
background = '#e3bfab' 
 
[colors.hints.end]
foreground = '#52443c' 
background = '#e3bfab' 
 
[colors.selection]
text = '#171210'
background = '#fbb88e'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#fbb88e' 
yellow = '#855230' 
blue = '#fbb88e' 
magenta = '#c7cb87' 
cyan = '#e3bfab' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 