config_version = 14

[backdrop]
blur_intensity = 0.29999999329447746
enabled = true

[bar.default]
background_opacity = 0.20000000000000001
border = "#ffffff2b"
border_width = 1.0
capsule = true
capsule_fill = "#ffffff"
capsule_opacity = 0.10000000000000001
capsule_padding = 7
center = [ "workspaces", "noctalia/notes:notes" ]
end = [
    "noctalia/screen_recorder:recorder",
    "media",
    "tray",
    "volume",
    "brightness",
    "battery",
    "notifications",
    "clock",
    "control-center"
]
hover_highlight = true
margin_edge = 6
margin_ends = 6
position = "top"
radius = 14
shadow = true
start = [ "launcher", "cpu", "temp", "ram", "active_window" ]

[battery.device."/org/freedesktop/UPower/devices/phone_dev_3C_1E_B5_15_96_98"]
warning_threshold = 10

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

    [calendar.account.iamcalegari20]
    type = "google"

[control_center]
sidebar_section = "full"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 0.20000000000000001
border = "#ffffff2b"
border_width = 1.0
enabled = true
icon_size = 42
monitors = [ "HDMI-A-1", "eDP-1" ]
pinned = [
    "Alacritty",
    "org.gnome.Nautilus",
    "md.obsidian.Obsidian",
    "firefox",
    "code",
    "MongoDB Compass",
    "postman",
    "org.mozilla.firefox.firefox-wah-TUodBlfE",
    "com.discordapp.Discord",
    "org.mozilla.firefox.firefox-wah-E2ZQDVLp",
    "com.spotify.Client",
    "page.codeberg.M23Snezhok.Vinyl"
]
position = "bottom"
radius = 16
shadow = true
show_dots = true

[hooks]
started = [ "/home/alan/.local/bin/dotsync" ]
theme_mode_changed = [ "/home/alan/.local/bin/dotsync" ]

[location]
address = "Belo Horizonte"

[lockscreen]
blur_intensity = 0.65000000000000002

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[osd]
position = "bottom_right"

[plugins]
enabled = [ "noctalia/notes", "noctalia/screen_recorder" ]

[shell]
avatar_path = "/home/alan/Pictures/avatar/face.jpg"
font_family = "Adwaita Sans"
niri_overview_type_to_launch_enabled = true
polkit_agent = true
screen_time_enabled = true
time_format = "{:%I:%M %p}"

    [shell.launcher]
    pinned = [
        "discord",
        "firefox",
        "Alacritty",
        "audacity",
        "org.gnome.Nautilus",
        "com.obsproject.Studio",
        "code",
        "io.github.kolunmi.Bazaar",
        "org.mozilla.firefox.firefox-wah-TUodBlfE",
        "page.codeberg.M23Snezhok.Vinyl",
        "org.musicbrainz.Picard",
        "com.spotify.Client",
        "mongodb-compass",
        "org.mozilla.firefox.firefox-wah-E2ZQDVLp",
        "md.obsidian.Obsidian",
        "com.getpostman.Postman",
        "postman",
        "org.nicotine_plus.Nicotine"
    ]

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    transparency_mode = "glass"

[theme]
builtin = "Tokyo-Night"
mode = "auto"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [
        "alacritty",
        "btop",
        "cava",
        "emacs",
        "foot",
        "ghostty",
        "gtk3",
        "gtk4",
        "helix",
        "hyprland",
        "kcolorscheme",
        "kitty",
        "labwc",
        "mango",
        "niri",
        "qt",
        "scroll",
        "starship",
        "sway",
        "wezterm"
    ]

[wallpaper]
directory = "/home/alan/Pictures/Wallpapers"
fill_color = "#000000"
fill_mode = "crop"
transition = [ "fade", "wipe", "disc", "stripes", "honeycomb" ]
transition_duration = 3000.0

    [wallpaper.automation]
    enabled = true
    interval_seconds = 300
    order = "random"

    [wallpaper.default]
    path = "/home/alan/Pictures/Wallpapers/dan-meyers-ucmEHogvn1g-unsplash.jpg"

    [wallpaper.last]
    path = "/home/alan/Pictures/Wallpapers/dan-meyers-ucmEHogvn1g-unsplash.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/alan/Pictures/Wallpapers/dan-meyers-ucmEHogvn1g-unsplash.jpg"